docker init
teract10s/bookStore pull request #10
Opened 2023-11-09 11:50 UTC by teract10s

2023-11-13 13:13 UTC, mmosii approved these changes
LGTM

2023-11-13 14:46 UTC, liliia-ponomarenko requested changes
Good job! Let’s  fix a few mistakes ;)

2023-11-13 14:46 UTC, liliia-ponomarenko commented on .env
> +DEBUG_PORT=5005
how happened that you pushed your .env to GitHub 😭 Please remove it! this file contains  sensitive  information

2023-11-13 14:46 UTC, liliia-ponomarenko commented on Dockerfile
> +EXPOSE 8080
add one empty line

2023-11-13 14:46 UTC, liliia-ponomarenko commented on docker-compose.yml
> +        "spring.datasource.url" : "jdbc:mysql://book-store-db:3306/book_store?serverTimezone=UTC",
use env variables  instead `3306/book_store`

2023-11-13 14:46 UTC, liliia-ponomarenko commented on docker-compose.yml
> +        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD"
Let’s  add drier property

2023-11-13 14:46 UTC, liliia-ponomarenko commented on src/main/resources/application.properties
>  server.servlet.context-path=/api
think which env variable  you can use in this file

2023-11-13 14:46 UTC, liliia-ponomarenko commented on .env
> +DEBUG_PORT=5005
you can add `.env.sample` but it file without values (for now it’s an optional comment)

2023-11-14 14:26 UTC, liliia-ponomarenko approved these changes
Great! 😊

2023-11-14 14:26 UTC, liliia-ponomarenko commented on .gitignore
> +
```suggestion
```

2023-11-16 10:42 UTC, merged