Add category
teract10s/bookStore pull request #7
Opened 2023-10-26 22:54 UTC by teract10s

2023-10-31 13:16 UTC, NazarSmith228 requested changes
Good job! Let's improve your solution

2023-10-31 13:16 UTC, NazarSmith228 commented on src/main/java/com/example/bookstore/controller/CategoryController.java
> +    @GetMapping("")
```suggestion
    @GetMapping
```

2023-10-31 13:16 UTC, NazarSmith228 commented on src/main/java/com/example/bookstore/controller/CategoryController.java
> +    ) {
```suggestion
            @PageableDefault(page = 0, size = 10, sort = "name") Pageable pageable) {
```

2023-10-31 13:16 UTC, NazarSmith228 commented on src/main/java/com/example/bookstore/controller/CategoryController.java
> +    ) {
```suggestion
    public List<BookResponseDto> getBooksByCategory(@PathVariable Long categoryId) {
```

2023-10-31 13:16 UTC, NazarSmith228 commented on src/main/java/com/example/bookstore/controller/CategoryController.java
> +    public CategoryResponseDto getCategory(@PathVariable Long id) {
will you validate `@PathVariable`?

if not - feel free to skip this comment

2023-10-31 13:16 UTC, NazarSmith228 commented on src/main/java/com/example/bookstore/controller/CategoryController.java
> +    @PostMapping("")
```suggestion
    @PostMapping
```

2023-10-31 13:16 UTC, NazarSmith228 commented on src/main/java/com/example/bookstore/controller/CategoryController.java
> +    ) {
```suggestion
    public CategoryResponseDto createCategory(@RequestBody @Valid CreateCategoryRequestDto categoryDto) {
```

2023-10-31 13:16 UTC, NazarSmith228 commented on src/main/java/com/example/bookstore/controller/CategoryController.java
> +    ) {
```suggestion
    public CategoryResponseDto updateCategory(@PathVariable Long id,
            @RequestBody @Valid CreateCategoryRequestDto categoryDto) {
```

2023-10-31 13:16 UTC, NazarSmith228 commented on src/main/java/com/example/bookstore/dto/category/CategoryResponseDto.java
> +public record CategoryResponseDto(Long id, String name, String description) {
please use the same formatting for all records

2023-10-31 13:16 UTC, NazarSmith228 commented on src/main/java/com/example/bookstore/mapper/BookMapper.java
>  public interface BookMapper {
shouldn't this mapper contain:
```
BookDtoWithoutCategoryIds toDtoWithoutCategories(Book book);
```
according to the task description

2023-10-31 13:16 UTC, NazarSmith228 commented on src/main/java/com/example/bookstore/controller/BookController.java
> +    public BookResponseDto updateBook(Authentication authentication, @PathVariable Long id,
pls ensure you did everything according to requirements

should the book response contain `categoryIds`?

2023-10-31 13:16 UTC, NazarSmith228 commented on src/main/java/com/example/bookstore/model/Book.java
> +    @ManyToMany()
```suggestion
    @ManyToMany
```

2023-10-31 13:16 UTC, NazarSmith228 commented on src/main/java/com/example/bookstore/repository/CategoryRepository.java
> +public interface CategoryRepository extends JpaRepository<Category, Long> {
`@Repository` missing

2023-10-31 13:16 UTC, NazarSmith228 commented on src/main/java/com/example/bookstore/service/impl/CategoryServiceImpl.java
> +        return categoryMapper.toDto(savedCategory);
this can be inlined

2023-11-01 06:51 UTC, teract10s commented on src/main/java/com/example/bookstore/controller/CategoryController.java
> +    ) {
In this case maven build will fail. I have to have less than 100 chars in one line

2023-11-03 08:30 UTC, NazarSmith228 approved these changes
LGTM, but please pay attention to my comment

2023-11-03 08:30 UTC, NazarSmith228 commented on src/main/java/com/example/bookstore/service/impl/BookServiceImpl.java
> +        bookMapper.setCategoryIds(dto, bookFromDb);
this method should be called automatically, since it is `@AfterMapping`

2023-11-03 10:25 UTC, merged